### ISSUE TITLE
Missing the MIT license that is standard for CCP open source projects.

### ISSUE THREAD

**Issue by Regner** [ccpgames/ccp-metrics#1]
Just a heads up. Know there isn't anything here yet but wanted to make sure it doesn't get forgotten. :)

**Comment by JauntyWard** [comment]
I'm just about to push some code up, the licence is there too! :)

**Comment by Regner** [comment]
Ignore me then. :)

**Comment by HakShak** [comment]
He's like a vulture.

Sent from my iPhone

On May 6, 2015, at 15:45, Regner Blok-Andersen <notifications@github.com<mailto:notifications@github.com>> wrote:


Ignore me then. :)
